# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createTransitiveSequences <- function(df_dbMart, numOfPatients, storeSeqDuringCreation = FALSE, outputDir, outputFilePrefix, numOfThreads = 1L) {
    .Call(`_tSPMPlus_createTransitiveSequences`, df_dbMart, numOfPatients, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads)
}

tSPMPlus <- function(df_dbMart, storeSeqDuringCreation = FALSE, outputDir, outputFilePrefix, numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_tSPMPlus`, df_dbMart, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

extractNonSparseSequences <- function(df_dbMart, storeSeqDuringCreation = FALSE, outputDir, outputFilePrefix, sparsityValue = 0.05, numOfThreads = 1L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_extractNonSparseSequences`, df_dbMart, storeSeqDuringCreation, outputDir, outputFilePrefix, sparsityValue, numOfThreads, returnDuration, durationPeriods, daysForCoOoccurence)
}

extractAllTransiviteSequences <- function(df_dbMart, storeSeqDuringCreation = FALSE, outputDir, outputFilePrefix, numOfThreads = 1L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_extractAllTransiviteSequences`, df_dbMart, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, returnDuration, durationPeriods, daysForCoOoccurence)
}

getSequencesWithEndPhenx <- function(df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, endPhenx, includeCorBuckets = TRUE, minDuration = 0L, storeSeqDuringCreation = FALSE, outputDir, outputFilePrefix, numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_getSequencesWithEndPhenx`, df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, endPhenx, includeCorBuckets, minDuration, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

getCandidateSequencesForPOI <- function(df_dbMart, minDuration, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenxOfInterrest, storeSeqDuringCreation = FALSE, outputDir, outputFilePrefix, numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_getCandidateSequencesForPOI`, df_dbMart, minDuration, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenxOfInterrest, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

