# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' transform the dbmart data frame to c++ structure
#' Function to create all transitive sequences
#' an store in binary format them to files.
#' @name transformDataFrameToStruct
#' @returns dbMart as c++ struct
#' @param  df_dbMart The dataframe that stores the numeric data mart.
NULL

#' Transforms the C++ representation used to store the sequences into R
#' 
#' Function to transform a vector of the C++ representation used to store the sequences into an R dataframe.
#' @name transformToDefaultDataFrame
#' @param sequences std::vector of the sequences that should be transformed into a R dataframe
#' @param returnDuration Boolean, if the duration should be included into the returned dataframe
NULL

#' summarize
#'
#' Function to summarize a set of sequences and  returing a R data frame that contains the summary.
#' that calls this functions with predefined parameters.
#' @name summarize
#' @returns The summary as data frame.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param lowerBucketThresholds IntegerVector, lower duration Thresholds for the duration buckets of the candidate sequences
#' @param includeDurations include duration buckets in the summary
#' @param sequences the vector containing the sequences to summarize
NULL

#' create all transitive Sequences
#' 
#' Function to create all transitive sequences
#' an store in binary format them to files.
#' 
#' @returns the overall number of sequences stored.
#' @param  df_dbMart The dataframe that stores the numeric data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @export
createTransitiveSequences <- function(df_dbMart, outputDir, outputFilePrefix, numOfThreads = 1L) {
    .Call(`_tSPMPlus_createTransitiveSequences`, df_dbMart, outputDir, outputFilePrefix, numOfThreads)
}

#' tSPMPlus
#'
#' Function to call the tSPM+ workflow, most of the other function provide by this package are wrapper functions
#' that calls this functions with predefined parameters.
#' 
#' @returns The sequences as data frame.
#' @param  df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param removeSparseSequences  Boolean parameter to control if the sparsity should be applied
#' @param sparsityValue          The numeric value for the sparsity. DEFAULT = 0.05.
#' @param createTemporalBuckets  Boolean flag if the the the sequences should be split up in dynamic buckets. Number of buckets min(4, max_duration(sequence)).
#' @param removeSparseTemporalBuckets Boolean, to control if the sparsity should be applied on the dynamic temporal buckets.
#' @param durationSparsity  Boolean flag to control if sparse sequences should be removed considering the duration periods of a sequence.
#' @param durationSparsityValue Numeric value.
#' @param patIdLength describes the number of digits that are used for the patient number.
#' @param returnDuration Boolean, controls if the data frame that is returns contains. 
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @export
tSPMPlus <- function(df_dbMart, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_tSPMPlus`, df_dbMart, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

#' extract Non Sparse Sequences
#'
#' Extracts all non sparse transitive sequences from the data mart, after converting it to numeric.
#'
#' @returns The sequences as data frame.
#' @param df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param sparsityValue          The numeric value for the sparsity. DEFAULT = 0.05.
#' @param returnDuration Boolean, controls if the data frame that is returns contains.
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, eg. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @export
extractNonSparseSequences <- function(df_dbMart, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", sparsityValue = 0.05, numOfThreads = 1L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_extractNonSparseSequences`, df_dbMart, storeSeqDuringCreation, outputDir, outputFilePrefix, sparsityValue, numOfThreads, returnDuration, durationPeriods, daysForCoOoccurence)
}

#' Extract All Transivite Sequences
#' 
#' Function to extract all transitive sequences.
#' 
#' @returns The sequences as data frame.
#' @param  df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param returnDuration Boolean, controls if the data frame that is returns contains.
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @export
extractAllTransiviteSequences <- function(df_dbMart, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", numOfThreads = 1L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_extractAllTransiviteSequences`, df_dbMart, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, returnDuration, durationPeriods, daysForCoOoccurence)
}

#' Get Sequences With Specific End Phenx
#' 
#' Function to extract all transitive sequences that end with given endPhenxs.
#' 
#' @returns The sequences as data frame.
#' @param df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param endPhenx IntegerVector, contains the phenx that sequences should end with.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param returnDuration Boolean, controls if the data frame that is returns contains. 
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @param minDuration the minimum duration a sequence must have, for j to be considered a candidate. Not Implemented at the moment!
#' @param bitShift  Integer, the number of bits used to shift the duration into sequnceID.
#' @param lengthOfPhenx describes the number of digits that represents a phenx in the sequence.
#' @param lowerBucketThresholds the lower thresholds for the temporal buckets, that are stored when the includeCorBuckets flag is set. 
#' @param includeCorBuckets Boolean, flag to control if the R data frame that is returned should contain columns for for the endPhenx and the buckets set in lowerBucketThresholds 
#' @param removeSparseSequences Boolean parameter to control if the sparsity should be applied.
#' @param sparsityValue The numeric value for the sparsity. DEFAULT = 0.05.
#' @param createTemporalBuckets Boolean flag if the the the sequences should be split up in dynamic buckets. Number of buckets min(4, max_duration(sequence)).
#' @param durationSparsity Boolean flag to control if sparse sequences should be removed considering the duration periods of a sequence.
#' @param durationSparsityValue Numeric value.
#' @param removeSparseTemporalBuckets Boolean, to control if the sparsity should be applied on the dynamic temporal buckets.
#' @param patIdLength Integer, describes the number of digits that are used for the patient number.
#' @param returnSummary Boolean, if return a summary of the sequences instead of the sequences
#' @param summaryOnPatientLevel bool, that defines if the summary should be on the patient level (counting occurrences for each patient) or on the dbMart level
#' @param returnCandidateDataFrame Boolean to controll is a candidate dataframe should be returned, if returnSummary and returnCandidateDataFrame are both false the default sequence dataframe is returned
#' @export
getSequencesWithEndPhenx <- function(df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, endPhenx, includeCorBuckets = FALSE, minDuration = 0L, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L, returnSummary = FALSE, summaryOnPatientLevel = FALSE, returnCandidateDataFrame = TRUE) {
    .Call(`_tSPMPlus_getSequencesWithEndPhenx`, df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, endPhenx, includeCorBuckets, minDuration, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence, returnSummary, summaryOnPatientLevel, returnCandidateDataFrame)
}

#' Get Sequences With Specific Start Phenx
#' 
#' Function to extract all transitive sequences that end with given endPhenxs.
#' @name getSequencesWithStartPhenx
#' @returns The sequences as data frame.
#' @param df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param startPhenx IntegerVector, contains the phenx that sequences should end with.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param returnDuration Boolean, controls if the data frame that is returns contains. 
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @param minDuration the minimum duration a sequence must have, for j to be considered a candidate. Not Implemented at the moment!
#' @param bitShift  Integer, the number of bits used to shift the duration into sequnceID.
#' @param lengthOfPhenx describes the number of digits that represents a phenx in the sequence.
#' @param lowerBucketThresholds the lower thresholds for the temporal buckets, that are stored when the includeCorBuckets flag is set. 
#' @param includeCorBuckets Boolean, flag to control if the R data frame that is returned should contain columns for for the endPhenx and the buckets set in lowerBucketThresholds 
#' @param removeSparseSequences Boolean parameter to control if the sparsity should be applied.
#' @param sparsityValue The numeric value for the sparsity. DEFAULT = 0.05.
#' @param createTemporalBuckets Boolean flag if the the the sequences should be split up in dynamic buckets. Number of buckets min(4, max_duration(sequence)).
#' @param durationSparsity Boolean flag to control if sparse sequences should be removed considering the duration periods of a sequence.
#' @param durationSparsityValue Numeric value.
#' @param removeSparseTemporalBuckets Boolean, to control if the sparsity should be applied on the dynamic temporal buckets.
#' @param patIdLength Integer, describes the number of digits that are used for the patient number.
#' @param summarize Boolean, if return a summary of the sequences instead of the sequences
#' @param returnCandidateDataFrame Boolean to controll is a candidate dataframe should be returned, if returnSummary and returnCandidateDataFrame are both false the default sequence dataframe is returned
#' @export
getSequencesWithStartPhenx <- function(df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenx, includeCorBuckets = FALSE, minDuration = 0L, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L, returnSummary = FALSE, summaryOnPatientLevel = FALSE, returnCandidateDataFrame = TRUE) {
    .Call(`_tSPMPlus_getSequencesWithStartPhenx`, df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenx, includeCorBuckets, minDuration, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence, returnSummary, summaryOnPatientLevel, returnCandidateDataFrame)
}

#' Get Sequences that start or end with a vector of given phenx
#' 
#' Function to extract all transitive sequences that end with given endPhenxs.
#' @name getSequencesContainingPhenx
#' @returns The sequences as data frame.
#' @param df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param phenxOfInterest IntegerVector, contains the phenx that sequences should end with.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param returnDuration Boolean, controls if the data frame that is returns contains. 
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @param minDuration the minimum duration a sequence must have, for j to be considered a candidate. Not Implemented at the moment!
#' @param bitShift  Integer, the number of bits used to shift the duration into sequnceID.
#' @param lengthOfPhenx describes the number of digits that represents a phenx in the sequence.
#' @param lowerBucketThresholds the lower thresholds for the temporal buckets, that are stored when the includeCorBuckets flag is set. 
#' @param includeCorBuckets Boolean, flag to control if the R data frame that is returned should contain columns for for the endPhenx and the buckets set in lowerBucketThresholds 
#' @param removeSparseSequences Boolean parameter to control if the sparsity should be applied.
#' @param sparsityValue The numeric value for the sparsity. DEFAULT = 0.05.
#' @param createTemporalBuckets Boolean flag if the the the sequences should be split up in dynamic buckets. Number of buckets min(4, max_duration(sequence)).
#' @param durationSparsity Boolean flag to control if sparse sequences should be removed considering the duration periods of a sequence.
#' @param durationSparsityValue Numeric value.
#' @param removeSparseTemporalBuckets Boolean, to control if the sparsity should be applied on the dynamic temporal buckets.
#' @param patIdLength Integer, describes the number of digits that are used for the patient number.
#' @param returnSummary Boolean, if return a summary of the sequences instead of the sequences
#' @param summaryOnPatientLevel bool, that defines if the summary should be on the patient level (counting occurrences for each patient) or on the dbMart level
#' @param returnCandidateDataFrame Boolean to controll is a candidate dataframe should be returned, if returnSummary and returnCandidateDataFrame are both false the default sequence dataframe is returned
#' @export
getSequencesContainingPhenx <- function(df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, phenxOfInterest, includeCorBuckets = FALSE, minDuration = 0L, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L, returnSummary = FALSE, summaryOnPatientLevel = FALSE, returnCandidateDataFrame = FALSE) {
    .Call(`_tSPMPlus_getSequencesContainingPhenx`, df_dbMart, bitShift, lengthOfPhenx, lowerBucketThresholds, phenxOfInterest, includeCorBuckets, minDuration, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence, returnSummary, summaryOnPatientLevel, returnCandidateDataFrame)
}

#' Get Candidate Sequences For Phenx Of Interest (POI)
#' 
#' Function to extract all sequences that end with phenx j, that is a end phenx for each phenx in startPhenxOfInterest.
#' @name getCandidateSequencesForPOI
#' @returns The sequences as data frame.
#' @param  df_dbMart The data frame that stores the data mart.
#' @param minDuration the minimum duration at least one sequence from type poi->j must have, for j to be considered a candidate.
#' @param bitShift  Integer, the number of bits used to shift the duration into sequnceID.
#' @param lengthOfPhenx Integer, number of digits used to represent the second phenx in the sequence.
#' @param lowerBucketThresholds IntegerVector, lower duration Thresholds for the duration buckets of the candidate sequences
#' @param startPhenxOfInterest IntegerVector, numeric representation of the POI.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param removeSparseSequences  Boolean parameter to control if the sparsity should be applied.
#' @param sparsityValue          The numeric value for the sparsity. DEFAULT = 0.05.
#' @param createTemporalBuckets  Boolean flag if the the the sequences should be split up in dynamic buckets. Number of buckets min(4, max_duration(sequence)).
#' @param removeSparseTemporalBuckets Boolean, to control if the sparsity should be applied on the dynamic temporal buckets.
#' @param durationSparsity  Boolean flag to control if sparse sequences should be removed considering the duration periods of a sequence.
#' @param durationSparsityValue Numeric value.
#' @param patIdLength Integer, describes the number of digits that are used for the patient number.
#' @param returnDuration Boolean, controls if the data frame that is returns contains.
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @export
getCandidateSequencesForPOI <- function(df_dbMart, minDuration, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenxOfInterest, storeSeqDuringCreation = FALSE, outputDir = "", outputFilePrefix = "", numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_getCandidateSequencesForPOI`, df_dbMart, minDuration, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenxOfInterest, storeSeqDuringCreation, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

#' Get Start Phenx From Sequence
#' 
#' Function to extract the start Phenx from a sequence.
#' @name getStartPhenxFromSequence
#' @returns The startPhenx of a sequence
#' @param  sequence  Integer.
#' @param phenxLength Integer, number of digits used to represent the second phenx in the sequence.
#' @export
getStartPhenxFromSequence <- function(sequence, phenxLength = 7L) {
    .Call(`_tSPMPlus_getStartPhenxFromSequence`, sequence, phenxLength)
}

#' Get End Phenx From Sequence
#' 
#' Function to extract the end Phenx from a sequence.
#' @name getEndPhenxFromSequence
#' @returns The endPhenx of a sequence.
#' @param  sequence  Integer.
#' @param phenxLength Integer, number of digits used to represent the second phenx in the sequence.
#' @export
getEndPhenxFromSequence <- function(sequence, phenxLength = 7L) {
    .Call(`_tSPMPlus_getEndPhenxFromSequence`, sequence, phenxLength)
}

#' Create a sequence from two phenx
#' 
#' Function create a sequence from two phenx.
#' @name createSequence
#' @returns Integer.
#' @param  firstPhenx  Integer.
#' @param  secondPhenx  Integer.
#' @param phenxLength Integer, number of digits used to represent the second phenx in the sequence.
#' @export
createSequence <- function(firstPhenx, secondPhenx, phenxLength = 7L) {
    .Call(`_tSPMPlus_createSequence`, firstPhenx, secondPhenx, phenxLength)
}

#' Sequences and summarizes all sequences in a dbmart
#' 
#' Summarizes the sequences in a dbmart
#' @name sequenceAndSummarize
#' @returns The summary as data frame.
#' @param  df_dbMart The data frame that stores the data mart.
#' @param outputDir The path as string to the directory where the sequences should be stored.
#' @param outputFilePrefix The string file prefix for the patient files storing the sequences.
#' @param numOfThreads The number of threads that should be used during sequencing.
#' @param storeSeqDuringCreation  Boolean parameter to control if the duration should be included in the sequence ID during creation, DEFAULT = FALSE.
#' @param removeSparseSequences  Boolean parameter to control if the sparsity should be applied.
#' @param sparsityValue          The numeric value for the sparsity. DEFAULT = 0.05.
#' @param createTemporalBuckets  Boolean flag if the the the sequences should be split up in dynamic buckets. Number of buckets min(4, max_duration(sequence)).
#' @param removeSparseTemporalBuckets Boolean, to control if the sparsity should be applied on the dynamic temporal buckets.
#' @param durationSparsity  Boolean flag to control if sparse sequences should be removed considering the duration periods of a sequence.
#' @param durationSparsityValue Numeric value.
#' @param patIdLength Integer, describes the number of digits that are used for the patient number.
#' @param durationPeriods Numeric, Upper threshold, stores the number of day in the time period, e.g. 30.471 for months, 364.25 for years. 
#' @param daysForCoOoccurence Integer, sets the upper threshold for the sequence duration so that they are counted as co-occurrence (meaning a duration of 0).
#' @param lowerBucketThresholds IntegerVector, lower duration Thresholds for the duration buckets of the candidate sequences
#' @param includeDurations include duration buckets in the summary
#' @param summaryOnPatientLevel bool, that defines if the summary should be on the patient level (counting occurrences for each patient) or on the dbMart level
#' @export
sequenceAndSummarize <- function(df_dbMart, lowerBucketThresholds, storeSeqDuringCreation = FALSE, includeDurations = FALSE, numOfThreads = 1L, outputDir = "", outputFilePrefix = "", removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, durationPeriods = 30.437, daysForCoOoccurence = 14L, summaryOnPatientLevel = FALSE) {
    .Call(`_tSPMPlus_sequenceAndSummarize`, df_dbMart, lowerBucketThresholds, storeSeqDuringCreation, includeDurations, numOfThreads, outputDir, outputFilePrefix, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, durationPeriods, daysForCoOoccurence, summaryOnPatientLevel)
}

