# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createTransitiveSequences <- function(df_dbMart, numOfPatients, outputDir, outputFilePrefix, numOfThreads) {
    .Call(`_tSPMPlus_createTransitiveSequences`, df_dbMart, numOfPatients, outputDir, outputFilePrefix, numOfThreads)
}

tSPMPlus <- function(df_dbMart, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_tSPMPlus`, df_dbMart, outputDir, outputFilePrefix, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

extractNonSparseSequences <- function(df_dbMart, outputDir, outputFilePrefix, sparsityValue, numOfThreads, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_extractNonSparseSequences`, df_dbMart, outputDir, outputFilePrefix, sparsityValue, numOfThreads, returnDuration, durationPeriods, daysForCoOoccurence)
}

extractAllTransiviteSequences <- function(df_dbMart, outputDir, outputFilePrefix, numOfThreads, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_extractAllTransiviteSequences`, df_dbMart, outputDir, outputFilePrefix, numOfThreads, returnDuration, durationPeriods, daysForCoOoccurence)
}

getSequencesWithCandidateEnd <- function(df_dbMart, outputDir, outputFilePrefix, minDuration, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenxOfInterrest, numOfThreads = 1L, removeSparseSequences = TRUE, sparsityValue = 0.05, createTemporalBuckets = FALSE, durationSparsity = FALSE, durationSparsityValue = 0, removeSparseTemporalBuckets = FALSE, patIdLength = 7L, returnDuration = TRUE, durationPeriods = 30.437, daysForCoOoccurence = 14L) {
    .Call(`_tSPMPlus_getSequencesWithCandidateEnd`, df_dbMart, outputDir, outputFilePrefix, minDuration, bitShift, lengthOfPhenx, lowerBucketThresholds, startPhenxOfInterrest, numOfThreads, removeSparseSequences, sparsityValue, createTemporalBuckets, durationSparsity, durationSparsityValue, removeSparseTemporalBuckets, patIdLength, returnDuration, durationPeriods, daysForCoOoccurence)
}

